url: http://blog.superfeedr.com
permalink: /:categories/:title/
highlighter: prism
markdown:    kramdown
paginate: 10
paginate_path: "/:num/"
gems:
  - jekyll-sitemap
defaults:
  -
    scope:
      paths: ""
      type: "posts"
    values:
      layout: post
      image: /images/superfeedr-logo.png
      author_name: Julien
      author_uri: http://ouvre-boite.com
      author_email_md5: b30ce50678f0e934eaa6697425c59dd7
